#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
#---------------------------- MCL - Tpitem ----------------------------#
#------------------------------- Config -------------------------------#
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
##
#Standard Rezept _[_, R0_ , _[_#
# auf false setzen um Standart zu aktivieren#
Rezeptabfrage: true

#Rezept einstelungen
Rezept:
    TpUhr:
        Zeile 1: _[_
        Zeile 2: R0R
        Zeile 3: _[_
        
#Name der Uhr
Uhr Name: '&cCityclock'

#Name des Huds
Hud Name: '&4Teleporter'

#Gui Größe
Gui scale: 6*9

#Anzahl der items beim craften
Clock anzahl: 8