name: Mcl-Tpitem
authors: [craftpi, FallvonWahnsinn, SkyLightEffect]
coder: [craftpi, FallvonWahnsinn, SkyLightEffect]
main: de.mclroleplay.main.MclTpitem
version: 1.1.0
api-version: 1.16
description: Dieses Plugin fügt dem Beruf Magier einen neuen craftbaren Gegentand hinzu.
website: www.minecraft-server.eu/server/index/216B4
softdepend: [MclRpEngine]
commands:

    minv:
        description: Admin TP interfase command
        usage: /minv
        
    mspawn:
        description: Spawn point für Tpitem
        usage: /mspawn <name>
        
    mremove:
        description: Löscht den angegebenen Spawn
        usage: /mremove <name>
        